import type { CaptionStyle } from "./types";

/**
 * Font stacks deliberately use fonts that ship with Windows/macOS so captions
 * render identically in the preview and in the exported file, with no web-font
 * loading and no network access.
 */
export const CAPTION_STYLES: CaptionStyle[] = [
  {
    id: "capcut-yellow",
    name: "Viral Yellow",
    font: "Anton, Impact, 'Arial Black', sans-serif",
    size: 0.072,
    weight: 900,
    color: "#ffe600",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.07,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.8,
    singleLine: true,
  },
  {
    id: "capcut-white",
    name: "Viral White",
    font: "Anton, Impact, 'Arial Black', sans-serif",
    size: 0.072,
    weight: 900,
    color: "#ffffff",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.07,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.8,
    singleLine: true,
  },
  {
    id: "capcut-green",
    name: "Neon Green",
    font: "Anton, Impact, 'Arial Black', sans-serif",
    size: 0.072,
    weight: 900,
    color: "#22c55e",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.07,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.8,
    singleLine: true,
  },
  {
    id: "capcut-cyan",
    name: "Cyan Ice",
    font: "Montserrat, Impact, 'Arial Black', sans-serif",
    size: 0.068,
    weight: 900,
    color: "#00f0ff",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.06,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.6,
    singleLine: true,
  },
  {
    id: "capcut-red",
    name: "Fire Red",
    font: "Anton, Impact, 'Arial Black', sans-serif",
    size: 0.072,
    weight: 900,
    color: "#ff2b2b",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.07,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.8,
    singleLine: true,
  },
  {
    id: "capcut-pink",
    name: "Pop Pink",
    font: "Poppins, 'Arial Black', sans-serif",
    size: 0.068,
    weight: 900,
    color: "#ff3e96",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.06,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.6,
    singleLine: true,
  },
  {
    id: "capcut-gold",
    name: "Luxury Gold",
    font: "Montserrat, 'Arial Black', sans-serif",
    size: 0.068,
    weight: 900,
    color: "#ffb800",
    stroke: "rgba(0, 0, 0, 0.85)",
    strokeWidth: 0.06,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.6,
    singleLine: true,
  },
  {
    id: "capcut-purple",
    name: "Purple Pop",
    font: "Poppins, Impact, sans-serif",
    size: 0.068,
    weight: 900,
    color: "#c084fc",
    stroke: "rgba(26, 8, 43, 0.85)",
    strokeWidth: 0.06,
    background: null,
    uppercase: true,
    shadow: true,
    letterSpacing: 0.6,
    singleLine: true,
  },
  {
    id: "capcut-black-box",
    name: "MrBeast Box",
    font: "Montserrat, 'Arial Black', sans-serif",
    size: 0.054,
    weight: 900,
    color: "#ffffff",
    stroke: "transparent",
    strokeWidth: 0,
    background: "rgba(0, 0, 0, 0.90)",
    uppercase: true,
    shadow: true,
    letterSpacing: 0.5,
    singleLine: true,
  },
  {
    id: "capcut-yellow-badge",
    name: "Yellow Pill",
    font: "Montserrat, 'Arial Black', sans-serif",
    size: 0.054,
    weight: 900,
    color: "#000000",
    stroke: "transparent",
    strokeWidth: 0,
    background: "#ffe600",
    uppercase: true,
    shadow: true,
    letterSpacing: 0.5,
    singleLine: true,
  },
  {
    id: "capcut-red-badge",
    name: "Red Badge",
    font: "Montserrat, 'Arial Black', sans-serif",
    size: 0.054,
    weight: 900,
    color: "#ffffff",
    stroke: "transparent",
    strokeWidth: 0,
    background: "#e11d48",
    uppercase: true,
    shadow: true,
    letterSpacing: 0.5,
    singleLine: true,
  },
  {
    id: "capcut-blue-badge",
    name: "Blue Badge",
    font: "Montserrat, 'Arial Black', sans-serif",
    size: 0.054,
    weight: 900,
    color: "#ffffff",
    stroke: "transparent",
    strokeWidth: 0,
    background: "#2563eb",
    uppercase: true,
    shadow: true,
    letterSpacing: 0.5,
    singleLine: true,
  },
  {
    id: "clean-modern",
    name: "Clean Outfit",
    font: "Outfit, Inter, sans-serif",
    size: 0.052,
    weight: 800,
    color: "#ffffff",
    stroke: "transparent",
    strokeWidth: 0,
    background: null,
    uppercase: false,
    shadow: true,
    letterSpacing: 0.6,
    singleLine: false,
  },
  {
    id: "doc-serif",
    name: "Documentary",
    font: "Georgia, 'Times New Roman', serif",
    size: 0.046,
    weight: 600,
    color: "#f4f1e8",
    stroke: "transparent",
    strokeWidth: 0,
    background: null,
    uppercase: false,
    shadow: true,
    letterSpacing: 0,
    singleLine: false,
  },
];

export const getStyle = (id?: string): CaptionStyle =>
  CAPTION_STYLES.find((s) => s.id === id) ?? CAPTION_STYLES[0];

export const TEXT_ANCHORS = [
  { id: "top", label: "Top" },
  { id: "middle", label: "Middle" },
  { id: "bottom", label: "Bottom" },
] as const;

export const BLEND_MODES: GlobalCompositeOperation[] = [
  "source-over",
  "screen",
  "multiply",
  "overlay",
  "soft-light",
  "lighten",
  "darken",
  "difference",
  "exclusion",
  "color-dodge",
  "hue",
  "saturation",
  "color",
  "luminosity",
];

export const BUILTIN_OVERLAYS: {
  id: string;
  label: string;
  blend: GlobalCompositeOperation;
  opacity: number;
}[] = [
  { id: "grain", label: "Film grain", blend: "overlay", opacity: 0.25 },
  { id: "particles", label: "Particles", blend: "screen", opacity: 0.5 },
  { id: "dust", label: "Dust", blend: "screen", opacity: 0.35 },
  { id: "vignette", label: "Vignette", blend: "multiply", opacity: 0.6 },
  { id: "scanlines", label: "Scanlines", blend: "multiply", opacity: 0.25 },
  { id: "light", label: "Light leak", blend: "screen", opacity: 0.3 },
];
