/**
 * Self-hosts the caption/display web fonts so the app never touches the network.
 *
 * Downloads the latin subset of each family/weight actually used by the caption
 * styles (see src/lib/editor/styles.ts) and emits:
 *
 *   src/assets/fonts/*.woff2   - the font binaries (committed to the repo)
 *   src/assets/fonts/fonts.css - @font-face rules with relative URLs
 *
 * styles.css imports fonts.css, so Vite fingerprints the woff2 files into the
 * renderer bundle and they ship inside the installer.
 *
 * Run: node scripts/setup-fonts.mjs
 * Re-run only when the caption font list changes; the output is committed.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(ROOT, "src", "assets", "fonts");

// Only what styles.ts actually references. Bebas Neue was in the old Google
// Fonts link but is never used, so it is intentionally absent here.
const FAMILIES = [
  ["Anton", [400]],
  ["Montserrat", [700, 800, 900]],
  ["Poppins", [700, 800, 900]],
  ["Outfit", [700, 800, 900]],
];

const API =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map(
    ([family, weights]) =>
      `family=${family.replace(/ /g, "+")}:wght@${weights.join(";")}`,
  ).join("&") +
  "&display=swap";

// A modern UA makes Google Fonts serve woff2 (and the subset comments we parse).
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36";

/** @param {string} url @param {RequestInit} [init] */
async function get(url, init = {}) {
  const res = await fetch(url, { ...init, headers: { "User-Agent": UA, ...(init.headers ?? {}) } });
  if (!res.ok) throw new Error(`GET ${url} -> HTTP ${res.status}`);
  return res;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const css = await (await get(API)).text();

  /** @type {{ family: string, weight: number, file: string }[]} */
  const files = [];
  let out = "/* Generated by scripts/setup-fonts.mjs - do not edit by hand. */\n";

  // Google emits `/* subset */ @font-face { ... }` blocks. Keep latin only.
  const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi)];

  for (const [, subset, block] of blocks) {
    if (subset.toLowerCase() !== "latin") continue;

    const family = block.match(/font-family:\s*'([^']+)'/i)?.[1];
    const weight = Number(block.match(/font-weight:\s*(\d+)/i)?.[1]);
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/i)?.[1];
    if (!family || !weight || !url) continue;

    const fileName = `${family.replace(/ /g, "")}-${weight}.woff2`;
    const bytes = Buffer.from(await (await (await get(url)).arrayBuffer()));
    await writeFile(join(OUT_DIR, fileName), bytes);
    files.push({ family, weight, file: fileName });
    console.log(`  ${fileName.padEnd(24)} ${(bytes.length / 1024).toFixed(1).padStart(6)} KB`);

    out += `\n@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url(./${fileName}) format('woff2');\n}\n`;
  }

  if (files.length === 0) {
    throw new Error("No latin woff2 faces parsed from the Google Fonts response.");
  }

  await writeFile(join(OUT_DIR, "fonts.css"), out);
  console.log(`wrote ${files.length} fonts -> src/assets/fonts/`);
}

main().catch((err) => {
  console.error("[setup-fonts] failed:", err?.message ?? err);
  process.exit(1);
});
